//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlenBotLogUploader.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LogsLocation {
            get {
                return ((string)(this["LogsLocation"]));
            }
            set {
                this["LogsLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TwitchChannelName {
            get {
                return ((string)(this["TwitchChannelName"]));
            }
            set {
                this["TwitchChannelName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DPSReportServer {
            get {
                return ((int)(this["DPSReportServer"]));
            }
            set {
                this["DPSReportServer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CustomTwitchName {
            get {
                return ((string)(this["CustomTwitchName"]));
            }
            set {
                this["CustomTwitchName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CustomTwitchOAuthPassword {
            get {
                return ((string)(this["CustomTwitchOAuthPassword"]));
            }
            set {
                this["CustomTwitchOAuthPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RaidarOAuth {
            get {
                return ((string)(this["RaidarOAuth"]));
            }
            set {
                this["RaidarOAuth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FirstTimeMinimise {
            get {
                return ((bool)(this["FirstTimeMinimise"]));
            }
            set {
                this["FirstTimeMinimise"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UploadLogs {
            get {
                return ((bool)(this["UploadLogs"]));
            }
            set {
                this["UploadLogs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UploadToTwitch {
            get {
                return ((bool)(this["UploadToTwitch"]));
            }
            set {
                this["UploadToTwitch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UploadToTwitchOnlySuccess {
            get {
                return ((bool)(this["UploadToTwitchOnlySuccess"]));
            }
            set {
                this["UploadToTwitchOnlySuccess"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UploadIgnoreFileSize {
            get {
                return ((bool)(this["UploadIgnoreFileSize"]));
            }
            set {
                this["UploadIgnoreFileSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CustomTwitchNameEnabled {
            get {
                return ((bool)(this["CustomTwitchNameEnabled"]));
            }
            set {
                this["CustomTwitchNameEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RaidarTags {
            get {
                return ((string)(this["RaidarTags"]));
            }
            set {
                this["RaidarTags"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RaidarEnabled {
            get {
                return ((bool)(this["RaidarEnabled"]));
            }
            set {
                this["RaidarEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GW2Location {
            get {
                return ((string)(this["GW2Location"]));
            }
            set {
                this["GW2Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ConnectToTwitch {
            get {
                return ((bool)(this["ConnectToTwitch"]));
            }
            set {
                this["ConnectToTwitch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FirstRun {
            get {
                return ((bool)(this["FirstRun"]));
            }
            set {
                this["FirstRun"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TrayMinimise {
            get {
                return ((bool)(this["TrayMinimise"]));
            }
            set {
                this["TrayMinimise"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TwitchCommandUploaderEnabled {
            get {
                return ((bool)(this["TwitchCommandUploaderEnabled"]));
            }
            set {
                this["TwitchCommandUploaderEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TwitchCommandLastLogEnabled {
            get {
                return ((bool)(this["TwitchCommandLastLogEnabled"]));
            }
            set {
                this["TwitchCommandLastLogEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("!uploader")]
        public string TwitchCommandUploader {
            get {
                return ((string)(this["TwitchCommandUploader"]));
            }
            set {
                this["TwitchCommandUploader"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("!lastlog")]
        public string TwitchCommandLastLog {
            get {
                return ((string)(this["TwitchCommandLastLog"]));
            }
            set {
                this["TwitchCommandLastLog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Log session")]
        public string SessionName {
            get {
                return ((string)(this["SessionName"]));
            }
            set {
                this["SessionName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SessionSuppressWebhooks {
            get {
                return ((bool)(this["SessionSuppressWebhooks"]));
            }
            set {
                this["SessionSuppressWebhooks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SessionOnlySuccess {
            get {
                return ((bool)(this["SessionOnlySuccess"]));
            }
            set {
                this["SessionOnlySuccess"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SessionMessage {
            get {
                return ((string)(this["SessionMessage"]));
            }
            set {
                this["SessionMessage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SessionSort {
            get {
                return ((int)(this["SessionSort"]));
            }
            set {
                this["SessionSort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<boss> kill: <log>")]
        public string BossTemplateSuccess {
            get {
                return ((string)(this["BossTemplateSuccess"]));
            }
            set {
                this["BossTemplateSuccess"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<boss> pull: <log>")]
        public string BossTemplateFail {
            get {
                return ((string)(this["BossTemplateFail"]));
            }
            set {
                this["BossTemplateFail"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int MaxConcurrentUploads {
            get {
                return ((int)(this["MaxConcurrentUploads"]));
            }
            set {
                this["MaxConcurrentUploads"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SessionSaveToFile {
            get {
                return ((bool)(this["SessionSaveToFile"]));
            }
            set {
                this["SessionSaveToFile"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("57")]
        public int ReleaseVersion {
            get {
                return ((int)(this["ReleaseVersion"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("57")]
        public int SavedVersion {
            get {
                return ((int)(this["SavedVersion"]));
            }
            set {
                this["SavedVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ArcAutoUpdate {
            get {
                return ((bool)(this["ArcAutoUpdate"]));
            }
            set {
                this["ArcAutoUpdate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TwitchCommandSongEnabled {
            get {
                return ((bool)(this["TwitchCommandSongEnabled"]));
            }
            set {
                this["TwitchCommandSongEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("!song")]
        public string TwitchCommandSong {
            get {
                return ((string)(this["TwitchCommandSong"]));
            }
            set {
                this["TwitchCommandSong"] = value;
            }
        }
    }
}
